// This file is automatically generated from your CSS. Any edits will be overwritten.
export const scaleSmallLarge: string
export const avatar: string
export const username: string
export const password: string
export const login: string
